application: whysaurus
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- appstats: on


handlers:
- url: /favicon\.ico
  static_files: static/img/triceratops_icon.png
  upload: static/img/triceratops_icon.png

- url: /static
  static_dir: static

- url: /static/css
  static_dir: static/css
  
- url: /static/js
  static_dir: static/css

- url: /job/.*
  script: WhySaurus.app
  login: admin
  secure: always
  
- url: /admin
  script: WhySaurus.app
  secure: always

- url: /.*
  script: WhySaurus.app
  secure: always
  

libraries:
- name: django
  version: "1.2"

# jinja is from gae-simpleauth, the others improve jinja functioning
- name: markupsafe
  version: "0.15"
- name: setuptools
  version: "0.6c11"
- name: jinja2
  version: "2.6"

# Trying to get ndb
- name: webapp2
  version: latest
  
